//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.42.
// 
namespace Canna.Prolog.Runtime.Help {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://canna/help.xsd", IsNullable=false)]
    public partial class Predicates {
        
        private PredicatesPredicate[] predicateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Predicate")]
        public PredicatesPredicate[] Predicate {
            get {
                return this.predicateField;
            }
            set {
                this.predicateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class PredicatesPredicate {
        
        private PredicatesPredicatePredicateIndicator predicateIndicatorField;
        
        private PredicatesPredicateArguments[] argumentsField;
        
        private string descriptionField;
        
        private string longDescField;
        
        private string[] samplesField;
        
        /// <remarks/>
        public PredicatesPredicatePredicateIndicator PredicateIndicator {
            get {
                return this.predicateIndicatorField;
            }
            set {
                this.predicateIndicatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Arguments")]
        public PredicatesPredicateArguments[] Arguments {
            get {
                return this.argumentsField;
            }
            set {
                this.argumentsField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string LongDesc {
            get {
                return this.longDescField;
            }
            set {
                this.longDescField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Sample", IsNullable=false)]
        public string[] Samples {
            get {
                return this.samplesField;
            }
            set {
                this.samplesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class PredicatesPredicatePredicateIndicator {
        
        private string functorField;
        
        private short arityField;
        
        /// <remarks/>
        public string Functor {
            get {
                return this.functorField;
            }
            set {
                this.functorField = value;
            }
        }
        
        /// <remarks/>
        public short Arity {
            get {
                return this.arityField;
            }
            set {
                this.arityField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class PredicatesPredicateArguments {
        
        private PredicatesPredicateArgumentsArgument argumentField;
        
        /// <remarks/>
        public PredicatesPredicateArgumentsArgument Argument {
            get {
                return this.argumentField;
            }
            set {
                this.argumentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class PredicatesPredicateArgumentsArgument {
        
        private string nameField;
        
        private PredicatesPredicateArgumentsArgumentDirection directionField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public PredicatesPredicateArgumentsArgumentDirection Direction {
            get {
                return this.directionField;
            }
            set {
                this.directionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum PredicatesPredicateArgumentsArgumentDirection {
        
        /// <remarks/>
        In,
        
        /// <remarks/>
        Out,
        
        /// <remarks/>
        Both,
    }
}
